### ISSUE TITLE
Is it possible to use LibCrowds as stripped-down IIIF-viewer?

### ISSUE THREAD

**Issue by arjanski** [LibCrowds/libcrowds-viewer#246]
Hello there,

I'd like to know if you think it's feasible to use LibCrowds as a simple IIIF-viewer to display IIIF images, without the tagging and other additional features? I saw that hiding buttons on the interface is easy (setting their property to "false"), but I'm wondering what will be displayed if the libcrowds-viewer selector has minimal space on the screen?

I'd probably like to use the tagging features in the future, but for now I am looking for a robust viewer. Do you LibCrowds is the way to go? Or does anyone have another suggestion?

Thank you!

**Comment by alexandermendes** [comment]
Hello! So, it probably largely depends on what you're building - if you're thinking of building a [Vue.js](https://vuejs.org/) frontend then this repo could (hopefully) be useful. But if you're using something else, and if you're just looking for a viewer (rather than one geared towards gathering annotations), I'd probably suggest checking some others out, like [Mirador](https://github.com/ProjectMirador/mirador) or [Universal Viewer](https://github.com/universalviewer).

**Comment by alexandermendes** [comment]
Mirador, Universal Viewer and LibCrowds Viewer are all based on [OpenSeadragon](http://openseadragon.github.io/)...you might want to explore that too
